# Site settings
title: Basit's Developer Blog # site title
description: >- # site description
  Basit's Developer Blog
lang: en-US # default lang
timezone: Europe/London # set your timezone
timezone: Europe/London # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/lamarrr/lamarrr.github.io # site repo [optional]
repo: https://github.com/lamarrr/lamarrr.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Basit Ayantunde # author name
  name: Basit Ayantunde # author name
  bio: >- # tell to the world
    Senior Systems Software Engineer at NVIDIA, ISO C++ WG21 Member, and Open-Source Contributor
  username: lamarrr # general username
  github: lamarrr # github username
  twitter: basit_ayantunde # twitter username
  facebook: Basit Ayantunde # facebook username
  email: basitayde@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://basit.pro" #
baseurl: 
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
